services:
  backend:
    image: mariopl25/skills-backend:latest
    container_name: skills-backend-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/competicion
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  frontend:
    image: mariopl25/skills-frontend:latest
    container_name: skills-frontend-container
    ports:
      - "4200:4200"

  db:
    image: mariopl25/skills-db:latest
    container_name: skills-db-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
    # volumes:
    #   - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql