apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: skills-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skills-backend
  minReplicas: 1  # Mínimo de réplicas
  maxReplicas: 10  # Máximo de réplicas
  targetCPUUtilizationPercentage: 40  # Escala si el uso de CPU supera el 40%